#pragma once

namespace NK
{
	enum SHADER_ATTRIBUTE_LOCATION
	{
		SHADER_ATTRIBUTE_LOCATION_POSITION		= 0,
		SHADER_ATTRIBUTE_LOCATION_NORMAL		= 1,
		SHADER_ATTRIBUTE_LOCATION_TEXCOORD_0	= 2,
		SHADER_ATTRIBUTE_LOCATION_TANGENT		= 3,
		SHADER_ATTRIBUTE_LOCATION_BITANGENT		= 4,
		SHADER_ATTRIBUTE_LOCATION_COLOUR_0		= 5,
	};
}