#pragma once

#include "CImGuiInspectorRenderable.h"

#include <Types/NekiTypes.h>


namespace NK
{

	//Attached to all entities that are to be synced across the network
	struct CNetworkSync final
	{
	public:
		std::uint32_t networkID; //Generated by the server when the entity is created - consistent between clients - used for communication (e.g.: client receives a "move networkID 2 to this position" packet)
		ClientIndex owner; //The client that owns this entity
	};
	
}
